name: nms
description: Nail Management System - A zero-cost management tool for nail salons.
publish_to: 'none'
version: 1.0.1+41

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.3.0
  image_picker: ^1.0.4
  image: ^4.1.3
  provider: ^6.0.5
  intl: ^0.20.2
  js: ^0.7.2
  fl_chart: ^1.2.0 # For revenue charts
  firebase_auth: ^6.4.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  share_plus: ^12.0.2
  path_provider: ^2.1.3
  file_picker: ^11.0.2
  firebase_analytics: ^12.4.3
  purchases_flutter: ^10.4.1
  url_launcher: ^6.3.2
  table_calendar: ^3.1.2
  device_calendar: ^4.3.2
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  fake_cloud_firestore: ^4.1.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icons/my_salon_icon.png"
